// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package MySchema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Employees struct {
	_tab flatbuffers.Table
}

func GetRootAsEmployees(buf []byte, offset flatbuffers.UOffsetT) *Employees {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Employees{}
	x.Init(buf, n+offset)
	return x
}

func FinishEmployeesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEmployees(buf []byte, offset flatbuffers.UOffsetT) *Employees {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Employees{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEmployeesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Employees) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Employees) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Employees) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Employees) Salary() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Employees) MutateSalary(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func EmployeesStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func EmployeesAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func EmployeesAddSalary(builder *flatbuffers.Builder, salary float32) {
	builder.PrependFloat32Slot(1, salary, 0.0)
}
func EmployeesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
